version: '3.7'

services:
  temporal:
    image: temporalio/auto-setup:latest  # Ensure to use the correct version
    container_name: temporal
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=postgres
      - DB_PORT=5432
      - DB_HOST=postgres
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal  # What Temporal auto-setup expects
      - POSTGRES_DB=temporal
      - YB_MASTER_IPS=yugabyte:7100
      - YB_CQL_PORT=9042
    ports:
      - "7233:7233"  # Temporal default port
    depends_on:
      postgres:
        condition: service_healthy
      yugabyte:
        condition: service_healthy
  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    ports:
      - "8080:8080" # Temporal Web UI
      
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "temporal"]
      interval: 15s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port

  yugabyte:
    image: yugabytedb/yugabyte:latest  # Use a stable Yugabyte version
    container_name: yugabyte
    environment:
      - YB_MASTER_IPS=yugabyte:7100
    ports:
      - "7100:7100"  # Yugabyte master port
      - "9000:9000"  # Yugabyte YSQL port
      - "9042:9042"  # Yugabyte CQL port
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --background=false

    volumes:
      - yugabyte_data:/mnt/disk0
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:7100", "|", "grep", "Yugabyte"]
      interval: 30s
      retries: 5

volumes:
  postgres_data:
  yugabyte_data:
